-- =========================================================
-- REGALIA - BASE DE DATOS LIMPIA
-- PostgreSQL
-- Script unificado a partir de migraciones V1 a V11
-- =========================================================

BEGIN;

-- =========================================================
-- 0. LIMPIEZA
-- =========================================================

DROP TABLE IF EXISTS comision CASCADE;
DROP TABLE IF EXISTS pago CASCADE;
DROP TABLE IF EXISTS tipo_pago CASCADE;
DROP TABLE IF EXISTS detalle_pedido CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS tipo_entrega CASCADE;
DROP TABLE IF EXISTS producto_imagen CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS tipo_producto CASCADE;
DROP TABLE IF EXISTS tienda_rubro CASCADE;
DROP TABLE IF EXISTS rubro CASCADE;
DROP TABLE IF EXISTS tienda CASCADE;
DROP TABLE IF EXISTS usuario_documento CASCADE;
DROP TABLE IF EXISTS vendedor CASCADE;
DROP TABLE IF EXISTS tipo_documento CASCADE;
DROP TABLE IF EXISTS categoria_documento CASCADE;
DROP TABLE IF EXISTS usuario_rol CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

-- =========================================================
-- 1. USUARIOS Y ROLES
-- =========================================================

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL,
    telefono VARCHAR(20),
    contrasena_hash VARCHAR(255) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_correo UNIQUE (correo)
);

CREATE TABLE rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_rol PRIMARY KEY (id_rol),
    CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE usuario_rol (
    id_usuario BIGINT NOT NULL,
    id_rol BIGINT NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario, id_rol),

    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario),

    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (id_rol)
        REFERENCES rol (id_rol)
);

-- =========================================================
-- 2. DOCUMENTOS, CATEGORIA DOCUMENTAL Y VENDEDOR
-- =========================================================

CREATE TABLE categoria_documento (
    id_categoria_documento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_categoria_documento PRIMARY KEY (id_categoria_documento),
    CONSTRAINT uq_categoria_documento_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_documento (
    id_tipo_documento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_categoria_documento BIGINT NOT NULL,
    nombre VARCHAR(80) NOT NULL,
    abreviatura VARCHAR(20) NOT NULL,
    longitud_minima INTEGER NOT NULL DEFAULT 1,
    longitud_maxima INTEGER NOT NULL DEFAULT 20,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_tipo_documento PRIMARY KEY (id_tipo_documento),
    CONSTRAINT uq_tipo_documento_nombre UNIQUE (nombre),
    CONSTRAINT uq_tipo_documento_abreviatura UNIQUE (abreviatura),

    CONSTRAINT fk_tipo_documento_categoria_documento
        FOREIGN KEY (id_categoria_documento)
        REFERENCES categoria_documento (id_categoria_documento),

    CONSTRAINT chk_tipo_documento_longitudes_validas
        CHECK (
            longitud_minima > 0
            AND longitud_maxima > 0
            AND longitud_minima <= longitud_maxima
        )
);

CREATE TABLE vendedor (
    id_vendedor BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_vendedor PRIMARY KEY (id_vendedor),

    CONSTRAINT fk_vendedor_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario),

    CONSTRAINT uq_vendedor_usuario UNIQUE (id_usuario)
);

CREATE TABLE usuario_documento (
    id_usuario_documento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    id_tipo_documento BIGINT NOT NULL,
    numero_documento VARCHAR(30) NOT NULL,
    estado_verificacion VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_usuario_documento PRIMARY KEY (id_usuario_documento),

    CONSTRAINT fk_usuario_documento_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario),

    CONSTRAINT fk_usuario_documento_tipo_documento
        FOREIGN KEY (id_tipo_documento)
        REFERENCES tipo_documento (id_tipo_documento),

    CONSTRAINT ck_usuario_documento_estado_verificacion
        CHECK (estado_verificacion IN (
            'PENDIENTE',
            'VERIFICADO',
            'RECHAZADO',
            'OBSERVADO'
        ))
);

CREATE UNIQUE INDEX uq_usuario_documento_usuario_tipo_activo
ON usuario_documento (id_usuario, id_tipo_documento)
WHERE estado = TRUE;

CREATE UNIQUE INDEX uq_usuario_documento_tipo_numero_verificado
ON usuario_documento (id_tipo_documento, numero_documento)
WHERE estado = TRUE
  AND estado_verificacion = 'VERIFICADO';

-- =========================================================
-- 3. TIENDA Y RUBROS
-- =========================================================

CREATE TABLE tienda (
    id_tienda BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_vendedor BIGINT NOT NULL,
    id_documento_fiscal BIGINT,
    nombre VARCHAR(120) NOT NULL,
    descripcion TEXT,
    direccion_referencia VARCHAR(255),
    estado_revision VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_tienda PRIMARY KEY (id_tienda),

    CONSTRAINT fk_tienda_vendedor
        FOREIGN KEY (id_vendedor)
        REFERENCES vendedor (id_vendedor),

    CONSTRAINT fk_tienda_documento_fiscal
        FOREIGN KEY (id_documento_fiscal)
        REFERENCES usuario_documento (id_usuario_documento),

    CONSTRAINT ck_tienda_estado_revision
        CHECK (estado_revision IN (
            'PENDIENTE',
            'APROBADA',
            'OBSERVADA',
            'RECHAZADA'
        ))
);

CREATE TABLE rubro (
    id_rubro BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_rubro PRIMARY KEY (id_rubro),
    CONSTRAINT uq_rubro_nombre UNIQUE (nombre)
);

CREATE TABLE tienda_rubro (
    id_tienda BIGINT NOT NULL,
    id_rubro BIGINT NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_tienda_rubro PRIMARY KEY (id_tienda, id_rubro),

    CONSTRAINT fk_tienda_rubro_tienda
        FOREIGN KEY (id_tienda)
        REFERENCES tienda (id_tienda),

    CONSTRAINT fk_tienda_rubro_rubro
        FOREIGN KEY (id_rubro)
        REFERENCES rubro (id_rubro)
);

-- =========================================================
-- 4. PRODUCTOS E IMAGENES
-- =========================================================

CREATE TABLE tipo_producto (
    id_tipo_producto BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_tipo_producto PRIMARY KEY (id_tipo_producto),
    CONSTRAINT uq_tipo_producto_nombre UNIQUE (nombre)
);

CREATE TABLE producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_tienda BIGINT NOT NULL,
    id_tipo_producto BIGINT NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    visible_en_tienda BOOLEAN NOT NULL DEFAULT FALSE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_producto PRIMARY KEY (id_producto),

    CONSTRAINT fk_producto_tienda
        FOREIGN KEY (id_tienda)
        REFERENCES tienda (id_tienda),

    CONSTRAINT fk_producto_tipo_producto
        FOREIGN KEY (id_tipo_producto)
        REFERENCES tipo_producto (id_tipo_producto),

    CONSTRAINT ck_producto_precio CHECK (precio > 0),
    CONSTRAINT ck_producto_stock CHECK (stock >= 0),

    CONSTRAINT ck_producto_visibilidad_estado
        CHECK (
            NOT (estado = FALSE AND visible_en_tienda = TRUE)
        )
);

CREATE UNIQUE INDEX uq_producto_tienda_nombre_activo
ON producto (id_tienda, UPPER(nombre))
WHERE estado = TRUE;

CREATE TABLE producto_imagen (
    id_producto_imagen BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_producto BIGINT NOT NULL,
    url_imagen VARCHAR(500) NOT NULL,
    orden INTEGER NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_producto_imagen PRIMARY KEY (id_producto_imagen),

    CONSTRAINT fk_producto_imagen_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto (id_producto),

    CONSTRAINT uq_producto_imagen_orden UNIQUE (id_producto, orden),
    CONSTRAINT ck_producto_imagen_orden CHECK (orden > 0)
);

-- =========================================================
-- 5. TIPO DE ENTREGA Y PEDIDO
-- =========================================================

CREATE TABLE tipo_entrega (
    id_tipo_entrega BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_tipo_entrega PRIMARY KEY (id_tipo_entrega),
    CONSTRAINT uq_tipo_entrega_nombre UNIQUE (nombre)
);

CREATE TABLE pedido (
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    id_tienda BIGINT NOT NULL,
    id_tipo_entrega BIGINT NOT NULL,
    fecha_entrega DATE NOT NULL,
    observacion TEXT,
    estado_pedido VARCHAR(30) NOT NULL DEFAULT 'RESERVADO',
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_pedido PRIMARY KEY (id_pedido),

    CONSTRAINT fk_pedido_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario),

    CONSTRAINT fk_pedido_tienda
        FOREIGN KEY (id_tienda)
        REFERENCES tienda (id_tienda),

    CONSTRAINT fk_pedido_tipo_entrega
        FOREIGN KEY (id_tipo_entrega)
        REFERENCES tipo_entrega (id_tipo_entrega),

    CONSTRAINT ck_pedido_estado_pedido
        CHECK (estado_pedido IN (
            'RESERVADO',
            'EN_PREPARACION',
            'LISTO',
            'ENTREGADO',
            'ANULADO'
        ))
);

CREATE TABLE detalle_pedido (
    id_detalle_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_pedido BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_detalle_pedido PRIMARY KEY (id_detalle_pedido),

    CONSTRAINT fk_detalle_pedido_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedido (id_pedido),

    CONSTRAINT fk_detalle_pedido_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto (id_producto),

    CONSTRAINT ck_detalle_pedido_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_pedido_precio CHECK (precio_unitario > 0)
);

-- =========================================================
-- 6. PAGOS Y COMISIONES
-- =========================================================

CREATE TABLE tipo_pago (
    id_tipo_pago BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_tipo_pago PRIMARY KEY (id_tipo_pago),
    CONSTRAINT uq_tipo_pago_nombre UNIQUE (nombre)
);

CREATE TABLE pago (
    id_pago BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_pedido BIGINT NOT NULL,
    id_tipo_pago BIGINT NOT NULL,
    monto NUMERIC(10, 2) NOT NULL,
    estado_pago VARCHAR(30) NOT NULL DEFAULT 'APROBADO',
    metodo_pago_pasarela VARCHAR(80),
    codigo_transaccion VARCHAR(150),
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_pago PRIMARY KEY (id_pago),

    CONSTRAINT fk_pago_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedido (id_pedido),

    CONSTRAINT fk_pago_tipo_pago
        FOREIGN KEY (id_tipo_pago)
        REFERENCES tipo_pago (id_tipo_pago),

    CONSTRAINT uq_pago_codigo_transaccion UNIQUE (codigo_transaccion),
    CONSTRAINT ck_pago_monto CHECK (monto > 0),

    CONSTRAINT ck_pago_estado_pago
        CHECK (estado_pago IN (
            'APROBADO',
            'REEMBOLSADO'
        ))
);

CREATE TABLE comision (
    id_comision BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_pago BIGINT NOT NULL,
    porcentaje NUMERIC(5, 2) NOT NULL,
    monto_comision NUMERIC(10, 2) NOT NULL,
    monto_neto_vendedor NUMERIC(10, 2) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_comision PRIMARY KEY (id_comision),

    CONSTRAINT fk_comision_pago
        FOREIGN KEY (id_pago)
        REFERENCES pago (id_pago),

    CONSTRAINT uq_comision_pago UNIQUE (id_pago),

    CONSTRAINT ck_comision_porcentaje
        CHECK (porcentaje >= 0 AND porcentaje <= 100),

    CONSTRAINT ck_comision_monto
        CHECK (monto_comision >= 0),

    CONSTRAINT ck_comision_monto_neto
        CHECK (monto_neto_vendedor >= 0)
);

-- =========================================================
-- 7. DATOS MAESTROS
-- =========================================================

INSERT INTO rol (nombre)
VALUES
    ('ADMIN'),
    ('CLIENTE'),
    ('VENDEDOR')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO tipo_pago (nombre, descripcion)
VALUES
    ('SEÑA', 'Pago inicial para reservar el pedido'),
    ('RESTANTE', 'Pago final del pedido')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO categoria_documento (nombre, descripcion, estado)
VALUES
    ('IDENTIDAD_PERSONAL', 'Documentos utilizados para validar la identidad personal del usuario', TRUE),
    ('FISCAL', 'Documentos utilizados para validar informacion tributaria o fiscal', TRUE),
    ('OTRO', 'Documentos que no pertenecen a identidad personal ni fiscal', TRUE)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO tipo_documento (
    id_categoria_documento,
    nombre,
    abreviatura,
    longitud_minima,
    longitud_maxima
)
VALUES
    (
        (SELECT id_categoria_documento FROM categoria_documento WHERE nombre = 'IDENTIDAD_PERSONAL'),
        'DOCUMENTO NACIONAL DE IDENTIDAD',
        'DNI',
        8,
        8
    ),
    (
        (SELECT id_categoria_documento FROM categoria_documento WHERE nombre = 'FISCAL'),
        'REGISTRO UNICO DE CONTRIBUYENTES',
        'RUC',
        11,
        11
    ),
    (
        (SELECT id_categoria_documento FROM categoria_documento WHERE nombre = 'IDENTIDAD_PERSONAL'),
        'CARNE DE EXTRANJERIA',
        'CE',
        9,
        12
    )
ON CONFLICT (abreviatura) DO NOTHING;

INSERT INTO rubro (nombre, descripcion, estado)
VALUES
    ('REGALOS PERSONALIZADOS', 'Tiendas enfocadas en regalos personalizados con nombres, fotos, frases o diseños especiales', TRUE),
    ('FLORES Y ARREGLOS', 'Tiendas que ofrecen ramos, flores y arreglos florales como regalo', TRUE),
    ('PELUCHES', 'Tiendas que ofrecen peluches, muñecos y regalos suaves', TRUE),
    ('DESAYUNOS SORPRESA', 'Tiendas que preparan desayunos sorpresa como detalle de regalo', TRUE),
    ('BOXES Y CANASTAS', 'Tiendas que venden cajas, boxes, canastas o combos de regalo', TRUE),
    ('CHOCOLATES Y DULCES', 'Tiendas que ofrecen chocolates, dulces, snacks o productos comestibles para regalo', TRUE),
    ('DETALLES ROMANTICOS', 'Tiendas enfocadas en detalles para parejas, aniversarios y fechas romanticas', TRUE),
    ('ACCESORIOS PERSONALIZADOS', 'Tiendas que ofrecen tazas, llaveros, cuadros, botellas, libretas u otros accesorios personalizados', TRUE)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO tipo_producto (nombre, estado)
VALUES
    ('REGALO FISICO', TRUE),
    ('REGALO PERSONALIZADO', TRUE),
    ('PACK O BOX', TRUE),
    ('PRODUCTO COMESTIBLE', TRUE),
    ('ARREGLO FLORAL', TRUE),
    ('ACCESORIO', TRUE)
ON CONFLICT (nombre) DO NOTHING;

COMMIT;
