-- =========================================================
-- V15 - Crear politicas comerciales
-- Centraliza reglas comerciales configurables:
-- - porcentaje de seña
-- - porcentaje de comisión
-- - futuras reglas comerciales sin alterar estructura de BD
-- =========================================================

CREATE TABLE politica_comercial (
    id_politica_comercial BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(80) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255),
    valor NUMERIC(10,2) NOT NULL,
    unidad VARCHAR(30) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_politica_comercial PRIMARY KEY (id_politica_comercial),

    CONSTRAINT ck_politica_comercial_codigo_formato
        CHECK (
            codigo = UPPER(codigo)
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_politica_comercial_valor_no_negativo
        CHECK (valor >= 0),

    CONSTRAINT ck_politica_comercial_unidad
        CHECK (unidad IN (
            'PORCENTAJE',
            'MONTO',
            'DIAS',
            'CANTIDAD'
        )),

    CONSTRAINT ck_politica_comercial_porcentaje_valido
        CHECK (
            unidad <> 'PORCENTAJE'
            OR valor <= 100
        )
);

CREATE UNIQUE INDEX uq_politica_comercial_codigo_activo
ON politica_comercial (codigo)
WHERE estado = TRUE;

INSERT INTO politica_comercial (
    codigo,
    nombre,
    descripcion,
    valor,
    unidad,
    estado
)
VALUES
(
    'PORCENTAJE_SENA',
    'Porcentaje de seña',
    'Porcentaje inicial que el cliente paga para reservar un pedido.',
    20.00,
    'PORCENTAJE',
    TRUE
),
(
    'PORCENTAJE_COMISION',
    'Porcentaje de comisión',
    'Porcentaje que REGALIA retiene sobre cada pago aprobado.',
    5.00,
    'PORCENTAJE',
    TRUE
);