-- =========================================================
-- V16 - Crear auditoria de eventos
-- Registra eventos relevantes de seguridad y administracion.
-- La auditoria conserva evidencia historica y no debe depender
-- completamente del ciclo de vida de las entidades de negocio.
-- =========================================================

CREATE TABLE auditoria_evento (
    id_auditoria_evento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_actor BIGINT,
    accion VARCHAR(80) NOT NULL,
    resultado VARCHAR(30) NOT NULL,
    auth_context VARCHAR(20),
    correo_actor VARCHAR(150),
    ip VARCHAR(45),
    user_agent VARCHAR(255),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_auditoria_evento PRIMARY KEY (id_auditoria_evento),

    CONSTRAINT fk_auditoria_evento_usuario_actor
        FOREIGN KEY (id_usuario_actor)
        REFERENCES usuario (id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT ck_auditoria_evento_accion
        CHECK (accion IN (
            'LOGIN_PUBLICO_EXITOSO',
            'LOGIN_ADMIN_EXITOSO',
            'LOGIN_ADMIN_FALLIDO',
            'LOGIN_PUBLICO_LIMITADO',
            'LOGIN_ADMIN_LIMITADO'
        )),

    CONSTRAINT ck_auditoria_evento_resultado
        CHECK (resultado IN (
            'EXITOSO',
            'FALLIDO',
            'LIMITADO'
        )),

    CONSTRAINT ck_auditoria_evento_auth_context
        CHECK (
            auth_context IS NULL
            OR auth_context IN ('PUBLIC', 'ADMIN')
        ),

    CONSTRAINT ck_auditoria_evento_correo_actor_formato
        CHECK (
            correo_actor IS NULL
            OR correo_actor = LOWER(correo_actor)
        )
);

CREATE INDEX idx_auditoria_evento_fecha_creacion
ON auditoria_evento (fecha_creacion DESC);

CREATE INDEX idx_auditoria_evento_accion
ON auditoria_evento (accion);

CREATE INDEX idx_auditoria_evento_correo_actor
ON auditoria_evento (correo_actor);

CREATE INDEX idx_auditoria_evento_id_usuario_actor
ON auditoria_evento (id_usuario_actor);