-- Persistencia de sesiones de checkout externas.
-- Permite correlacionar Mercado Pago con el pedido real sin crear pedidos antes de confirmar el pago.

CREATE TABLE checkout_session (
    id_checkout_session BIGINT GENERATED BY DEFAULT AS IDENTITY,
    external_reference VARCHAR(150) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    preference_id VARCHAR(150),
    payment_id VARCHAR(150),
    estado_checkout VARCHAR(30) NOT NULL DEFAULT 'CREADA',
    estado_pago VARCHAR(30),
    provider_status_detail VARCHAR(150),
    id_usuario BIGINT NOT NULL,
    id_tienda BIGINT NOT NULL,
    id_tipo_entrega BIGINT NOT NULL,
    id_tipo_pago BIGINT NOT NULL,
    codigo_tipo_pago VARCHAR(50) NOT NULL,
    fecha_entrega DATE NOT NULL,
    observacion TEXT,
    subtotal NUMERIC(10,2) NOT NULL,
    monto_inicial NUMERIC(10,2) NOT NULL,
    saldo_restante NUMERIC(10,2) NOT NULL,
    moneda VARCHAR(10) NOT NULL DEFAULT 'PEN',
    id_pedido BIGINT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT pk_checkout_session PRIMARY KEY (id_checkout_session),
    CONSTRAINT uq_checkout_session_external_reference UNIQUE (external_reference),
    CONSTRAINT uq_checkout_session_payment_id UNIQUE (payment_id),
    CONSTRAINT fk_checkout_session_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_checkout_session_tienda FOREIGN KEY (id_tienda) REFERENCES tienda (id_tienda),
    CONSTRAINT fk_checkout_session_tipo_entrega FOREIGN KEY (id_tipo_entrega) REFERENCES tipo_entrega (id_tipo_entrega),
    CONSTRAINT fk_checkout_session_tipo_pago FOREIGN KEY (id_tipo_pago) REFERENCES tipo_pago (id_tipo_pago),
    CONSTRAINT fk_checkout_session_pedido FOREIGN KEY (id_pedido) REFERENCES pedido (id_pedido),
    CONSTRAINT chk_checkout_session_estado CHECK (estado_checkout IN ('CREADA', 'PENDIENTE', 'APROBADA', 'RECHAZADA', 'EXPIRADA', 'ERROR')),
    CONSTRAINT chk_checkout_session_subtotal CHECK (subtotal > 0),
    CONSTRAINT chk_checkout_session_monto_inicial CHECK (monto_inicial > 0),
    CONSTRAINT chk_checkout_session_saldo_restante CHECK (saldo_restante >= 0)
);

CREATE INDEX idx_checkout_session_estado_checkout ON checkout_session (estado_checkout);
CREATE INDEX idx_checkout_session_usuario ON checkout_session (id_usuario);
CREATE INDEX idx_checkout_session_pedido ON checkout_session (id_pedido);

CREATE TABLE checkout_session_item (
    id_checkout_session_item BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_checkout_session BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    nombre_producto VARCHAR(150) NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT pk_checkout_session_item PRIMARY KEY (id_checkout_session_item),
    CONSTRAINT fk_checkout_session_item_session FOREIGN KEY (id_checkout_session) REFERENCES checkout_session (id_checkout_session),
    CONSTRAINT fk_checkout_session_item_producto FOREIGN KEY (id_producto) REFERENCES producto (id_producto),
    CONSTRAINT uq_checkout_session_item_producto UNIQUE (id_checkout_session, id_producto),
    CONSTRAINT chk_checkout_session_item_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_checkout_session_item_precio CHECK (precio_unitario > 0),
    CONSTRAINT chk_checkout_session_item_subtotal CHECK (subtotal > 0)
);

CREATE INDEX idx_checkout_session_item_session ON checkout_session_item (id_checkout_session);
