-- Base para SSO: una cuenta REGALIA puede vincular identidades externas.
-- La contrasena local queda opcional para usuarios creados desde proveedores OAuth.

ALTER TABLE usuario
    ALTER COLUMN contrasena_hash DROP NOT NULL;

CREATE TABLE usuario_identidad (
    id_usuario_identidad BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    proveedor VARCHAR(30) NOT NULL,
    proveedor_subject VARCHAR(255) NOT NULL,
    correo_proveedor VARCHAR(150) NOT NULL,
    correo_verificado BOOLEAN NOT NULL DEFAULT FALSE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT pk_usuario_identidad PRIMARY KEY (id_usuario_identidad),
    CONSTRAINT fk_usuario_identidad_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT uq_usuario_identidad_proveedor_subject UNIQUE (proveedor, proveedor_subject),
    CONSTRAINT uq_usuario_identidad_usuario_proveedor UNIQUE (id_usuario, proveedor),
    CONSTRAINT chk_usuario_identidad_proveedor CHECK (proveedor IN ('GOOGLE'))
);

CREATE INDEX idx_usuario_identidad_usuario ON usuario_identidad (id_usuario);
CREATE INDEX idx_usuario_identidad_correo ON usuario_identidad (correo_proveedor);
