-- Base generica para tokens de seguridad de usuario.
-- Permite verificar correos, recuperar contrasenas y validar cambios de correo sin crear tablas por cada flujo.

ALTER TABLE usuario
    ADD COLUMN correo_verificado BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN fecha_verificacion_correo TIMESTAMP;

UPDATE usuario u
SET correo_verificado = TRUE,
    fecha_verificacion_correo = COALESCE(u.fecha_actualizacion, u.fecha_creacion)
WHERE EXISTS (
    SELECT 1
    FROM usuario_identidad ui
    WHERE ui.id_usuario = u.id_usuario
      AND ui.proveedor = 'GOOGLE'
      AND ui.correo_verificado = TRUE
      AND ui.estado = TRUE
);

CREATE TABLE usuario_token_seguridad (
    id_usuario_token_seguridad BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    tipo_token VARCHAR(40) NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    fecha_expiracion TIMESTAMP NOT NULL,
    fecha_consumo TIMESTAMP,
    intentos INTEGER NOT NULL DEFAULT 0,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT pk_usuario_token_seguridad PRIMARY KEY (id_usuario_token_seguridad),
    CONSTRAINT fk_usuario_token_seguridad_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT chk_usuario_token_seguridad_tipo CHECK (tipo_token IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'EMAIL_CHANGE')),
    CONSTRAINT chk_usuario_token_seguridad_intentos CHECK (intentos >= 0)
);

CREATE INDEX idx_usuario_token_seguridad_usuario_tipo
    ON usuario_token_seguridad (id_usuario, tipo_token);

CREATE INDEX idx_usuario_token_seguridad_token_hash
    ON usuario_token_seguridad (token_hash);

CREATE INDEX idx_usuario_token_seguridad_expiracion
    ON usuario_token_seguridad (fecha_expiracion);
