CREATE TABLE limite_seguridad_solicitud (
    id_limite_seguridad_solicitud BIGINT GENERATED BY DEFAULT AS IDENTITY,
    clave_politica VARCHAR(80) NOT NULL,
    tipo_sujeto VARCHAR(20) NOT NULL,
    clave_sujeto VARCHAR(255) NOT NULL,
    inicio_ventana TIMESTAMP NOT NULL,
    cantidad_solicitudes INTEGER NOT NULL DEFAULT 0,
    fecha_ultima_solicitud TIMESTAMP NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_limite_seguridad_solicitud
        PRIMARY KEY (id_limite_seguridad_solicitud),

    CONSTRAINT uq_limite_seguridad_solicitud_contexto
        UNIQUE (clave_politica, tipo_sujeto, clave_sujeto),

    CONSTRAINT chk_limite_seguridad_solicitud_cantidad
        CHECK (cantidad_solicitudes >= 0),

    CONSTRAINT chk_limite_seguridad_solicitud_tipo_sujeto
        CHECK (tipo_sujeto IN ('USUARIO', 'CORREO', 'IP'))
);

-- Invalida JWT emitidos antes de un cambio de credenciales sin crear una tabla de sesiones.
ALTER TABLE usuario
    ADD COLUMN version_autenticacion INTEGER NOT NULL DEFAULT 0;
