CREATE TABLE tienda_imagen (
    id_tienda_imagen BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_tienda BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    url_imagen VARCHAR(500) NOT NULL,
    clave_almacenamiento VARCHAR(500) NOT NULL,
    tipo_contenido VARCHAR(100) NOT NULL,
    ancho INTEGER NOT NULL,
    alto INTEGER NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_tienda_imagen PRIMARY KEY (id_tienda_imagen),
    CONSTRAINT fk_tienda_imagen_tienda
        FOREIGN KEY (id_tienda) REFERENCES tienda (id_tienda),
    CONSTRAINT uq_tienda_imagen_tienda_tipo UNIQUE (id_tienda, tipo),
    CONSTRAINT chk_tienda_imagen_tipo CHECK (tipo IN ('LOGO', 'PORTADA')),
    CONSTRAINT chk_tienda_imagen_dimensiones CHECK (ancho > 0 AND alto > 0)
);
