-- Representa el cumplimiento de la entrega actual de un pedido.
-- No es un historial de auditoria: para el MVP hay una entrega por pedido.
CREATE TABLE pedido_cumplimiento (
    id_pedido_cumplimiento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_pedido BIGINT NOT NULL,
    metodo_confirmacion VARCHAR(30) NOT NULL,
    codigo_hash VARCHAR(255) NOT NULL,
    fecha_expiracion_codigo TIMESTAMP NOT NULL,
    intentos_codigo INTEGER NOT NULL DEFAULT 0,
    fecha_listo TIMESTAMP NOT NULL,
    fecha_confirmacion TIMESTAMP,
    id_usuario_confirmador BIGINT,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_pedido_cumplimiento PRIMARY KEY (id_pedido_cumplimiento),
    CONSTRAINT uq_pedido_cumplimiento_pedido UNIQUE (id_pedido),
    CONSTRAINT fk_pedido_cumplimiento_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido (id_pedido),
    CONSTRAINT fk_pedido_cumplimiento_usuario_confirmador
        FOREIGN KEY (id_usuario_confirmador) REFERENCES usuario (id_usuario),
    CONSTRAINT chk_pedido_cumplimiento_metodo
        CHECK (metodo_confirmacion IN ('CODIGO_ENTREGA')),
    CONSTRAINT chk_pedido_cumplimiento_intentos
        CHECK (intentos_codigo >= 0)
);
