-- =========================================================
-- V6 - Reestructuración de documentos y perfil vendedor
-- Crea usuario_documento para registrar documentos reutilizables por usuario.
-- Limpia vendedor para que represente solo el perfil comercial.
-- Permite varias tiendas por vendedor y documento fiscal opcional en tienda.
-- =========================================================

ALTER TABLE vendedor
ADD COLUMN fecha_actualizacion TIMESTAMP;

CREATE TABLE usuario_documento (
    id_usuario_documento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    id_tipo_documento BIGINT NOT NULL,
    numero_documento VARCHAR(30) NOT NULL,
    estado_verificacion VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP,

    CONSTRAINT pk_usuario_documento PRIMARY KEY (id_usuario_documento),

    CONSTRAINT fk_usuario_documento_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario),

    CONSTRAINT fk_usuario_documento_tipo_documento
        FOREIGN KEY (id_tipo_documento)
        REFERENCES tipo_documento (id_tipo_documento),

    CONSTRAINT uq_usuario_documento_tipo_numero
        UNIQUE (id_tipo_documento, numero_documento),

    CONSTRAINT ck_usuario_documento_estado_verificacion
        CHECK (estado_verificacion IN (
            'PENDIENTE',
            'VERIFICADO',
            'RECHAZADO',
            'OBSERVADO'
        ))
);

INSERT INTO usuario_documento (
    id_usuario,
    id_tipo_documento,
    numero_documento,
    estado_verificacion,
    estado,
    fecha_creacion,
    fecha_actualizacion
)
SELECT
    v.id_usuario,
    v.id_tipo_documento,
    v.numero_documento,
    'PENDIENTE',
    TRUE,
    v.fecha_creacion,
    v.fecha_actualizacion
FROM vendedor v
WHERE v.id_tipo_documento IS NOT NULL
  AND v.numero_documento IS NOT NULL
ON CONFLICT (id_tipo_documento, numero_documento) DO NOTHING;

ALTER TABLE vendedor
DROP CONSTRAINT IF EXISTS fk_vendedor_tipo_documento;

ALTER TABLE vendedor
DROP CONSTRAINT IF EXISTS uq_vendedor_documento;

ALTER TABLE vendedor
DROP COLUMN IF EXISTS id_tipo_documento;

ALTER TABLE vendedor
DROP COLUMN IF EXISTS numero_documento;

ALTER TABLE tienda
DROP CONSTRAINT IF EXISTS uq_tienda_vendedor;

ALTER TABLE tienda
ADD COLUMN id_documento_fiscal BIGINT;

ALTER TABLE tienda
ADD CONSTRAINT fk_tienda_documento_fiscal
    FOREIGN KEY (id_documento_fiscal)
    REFERENCES usuario_documento (id_usuario_documento);