spring.application.name=regalia-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/regalia_db
spring.datasource.username=regalia_user
spring.datasource.password=RegaliaApp2026!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

regalia.security.jwt.secret=${JWT_SECRET:UmVnYWxpYUFwcFNlY3JldEtleUZvckRldk9ubHlNdXN0QmVDaGFuZ2VkSW5Qcm9kdWN0aW9u}
regalia.security.jwt.expiration-minutes=60

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080